version: "3.8"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: scanner
      POSTGRES_PASSWORD: scanner
      POSTGRES_DB: scannerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scanner -d scannerdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
  
  scanner:
    build: ./scanner
    volumes:
      - ./frontend:/app/frontend
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
    driver: bridge
    name: backend

volumes:
  postgres_data: