services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: scanner
      POSTGRES_PASSWORD: scanner
      POSTGRES_DB: scannerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  scanner:
    build: ./scanner
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - db
  
volumes:
  postgres_data:
  